// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:13bd1342-05a9-4684-b99a-2d2d58bda04b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ec8cXvkzL",
    "aws_user_pools_web_client_id": "rg943buaubj3rsdr8ccbk65hu",
    "oauth": {}
};


export default awsmobile;
